services:
  api-1: &api
    image: gasparin/rinha-backend-2026@sha256:6948918e46dc3d7a821da6510c979c24e9ddf806997cff4eb64e185d2fca0053
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          memory: '160M'
          cpus: "0.45"

  api-2:
    <<: *api

  haproxy:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          memory: '30M'
          cpus: "0.10"

networks:
  rinha-net:
    driver: bridge
