services:
  api-1: &api
    image: gasparin/rinha-backend-2026@sha256:7dd5de1dededbf9dab701a3067c19de5fa898643ca67aa006bc374a4f7cdf0cf
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - rinha-net
    cpuset: "0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: '160M'
          cpus: "0.45"

  api-2:
    <<: *api
    cpuset: "1"

  haproxy:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - rinha-net
    cpuset: "2,3"  
    deploy:
      resources:
        limits:
          memory: '30M'
          cpus: "0.10"

networks:
  rinha-net:
    driver: bridge
